# Generated by Django 5.0.6 on 2026-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=50)),
                ('parent_contact', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
