# Generated by Django 5.0.6 on 2026-09-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_system', '0003_student_added_by_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='can_add_students',
            field=models.BooleanField(default=False),
        ),
    ]
