# Generated by Django 5.0.6 on 2026-09-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_system', '0009_remove_timetable_day_remove_timetable_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
