# Generated by Django 5.0.6 on 2026-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_system', '0010_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_contact',
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, help_text='Fill if parents are unavailable', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_photo',
            field=models.ImageField(blank=True, null=True, upload_to='guardian_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relationship',
            field=models.CharField(blank=True, help_text='e.g., Uncle, Aunt, Grandparent', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, help_text='Home address or residence location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, help_text='Required if joining Senior 2 or above', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique student ID', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
