# Generated by Django 5.0.6 on 2026-10-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_system', '0012_alter_gradereport_options_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradereport',
            options={},
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
